"""empty message

Revision ID: 73d7f8491013
Revises: 
Create Date: 2017-04-11 08:50:25.762133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d7f8491013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer1', sa.Column('marital', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer1', 'marital')
    # ### end Alembic commands ###
